### ISSUE TITLE
need to install GO to build Rye-fyne?

### ISSUE THREAD

**Issue by HFolkertH** [refaktor/rye-front#31]
The combination Rye & Fyne looks very nice. But your instruction to get the examples running seem to mis some steps. Doing \.build on Windows just gives an error "command not found". Some steps to build fyne-rye seem to be missiing. Do I need to install also GO itself?

Is it not possible to create an easy to  install rye-fyne executable for Windows/Linux/Mac? It would make experimenting with those GUI-examples for non-techs a lot easier.

**Comment by refaktor** [comment]
You are correct. Rye-fyne's readme hasn't yet been updated and we should also add workflows that would make builds available. We have all that at main Rye repository, but Rye-fyne is just starting to work, and this is not there yet. Since I made the Cookbook page and published it it only makes sense to hurry up and add this also. I will try to do both in next few days. Thanks for the interest!

Currently, you would need Go installed, then you would run commands to install Fyne as per Fyne's install instructions and then run `./build`. 2 contributtors do this on Windows, but I haven't yet done it there, so I'm not sure how simple or not it's to install Fyne on Windows. I will try this too and document it.

**Comment by refaktor** [comment]
@HFolkertH This was the first time I tried to use Rye or Rye-fyne on Windows. I saw that ansi codes (colors / etc) don't work in Windows commandline at all. I fixed that and re-uploaded here: 

https://github.com/refaktor/rye-fyne/releases/tag/testbuild3

Besides the console I didn't get to test it yet. You can try it and please report if there are any problems. I will keep working on this, next I will make builds for all 3 OSes.

**Comment by HFolkertH** [comment]
I am trying to install rye and fyne on my old macbook also. I have installed Go. That works. I have also installed Rye. Works also.
But how to build rye-fyne? 
Is the first instruction below about 'build' correct?  Where does that Rye-fyne directory come from? Should I make an empty folder named rye-fyne in the rye-folder?

![image](https://github.com/user-attachments/assets/b495f92c-6dc2-453e-a9f9-545e052b2e22)

**Comment by refaktor** [comment]
Ah, I thought you were on Windows. We now have Windows, Linux and MacOS rye-fyne binaries. I tested Linux and Windows and a colleague tested in to MacOS and it worked:
![Screenshot_2024-10-03_at_08 23 46](https://github.com/user-attachments/assets/89de1708-9128-4598-845c-f1bfcca4288a).

You can get the latest build here, but there will be new ones soon: https://github.com/refaktor/rye-fyne/releases/tag/23

In this case you don't need Go, you just download and unpack the binary and run rye-fyne and you will enter console where you can run for example this code: `cc fyne , app .window "Hello" |set-content label "world" |show-and-run`

About your question. If you have Go installed and you want to run ./build ... you have to download this repository we're currently in (rye-fyne): https://github.com/refaktor/rye-fyne/ 

You can do so by downloading Zip on the top-right of the page or if you use Git you can
`git clone https://github.com/refaktor/rye-fyne.git` 
`git clone git@github.com:refaktor/rye-fyne.git`

In this folder that you download or git clone (rye-fyne), you can then run ./build . You basically don't need to have regular rye for this.

**Comment by HFolkertH** [comment]
Hi Refactor,

Thanks for your nice work. 
I actually have gathered lots of laptops in the last 30 years; running   windows, Mac and Linux .
Hobby programming with Rebol, Red, Arturo and lately Rye-fyne.




⁣TypeApp voor Android downloaden ​

Op 3 okt. 2024 12:01, om 12:01, Refaktor ***@***.***> schreef:

**Comment by refaktor** [comment]
You are welcome. Thanks for the interest. The build process seems to work at least in general on all 3 OS-es, so I will close this Issue. I will be adding rye-fyne download links to this repo README and to ryeang.org front page.
